Fix _pymod2pkg_translate when skip_pyversion is None
[1] ensured proper order for py_vers when using pymod2pkg, however
it did not consider the chance that skip_pyversion is None. In this
case, it failed with:

TypeError: argument of type 'NoneType' is not iterable

This patch ensures that it works even when skip_pyversion is None.

[1] - https://review.opendev.org/662719

Change-Id: Iac7dda35b44edf4a7af31129d9055280aa37df01